name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build the app
        run: scripts/buildprod.sh
